"""Add is_admin to User model

Revision ID: 935c3d8bc3b7
Revises: 61bd67e1eba3
Create Date: 2025-07-11 18:08:28.261490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935c3d8bc3b7'
down_revision: Union[str, None] = '61bd67e1eba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
